config/routes.rb
Rails.application.routes.draw do
  
  resources :results

  resources :available_systems
	resources :tryouts

	get 'admin' => 'admin#index'
  get 'sessions' => 'sessions#new'
	
  post 'sessions' => 'sessions#login'

	controller :sessions do
		get 'login' => :new
		post 'login' => :login
		get 'logout' => :destroy
	end
	controller :users do
    get 'have' => :index
  	get 'index' => :have
  end
	controller :tryout do
		get 'display' => :index
		get 'check' => :results
		get 'reader' => :reader
		get 'pie' => :piechart
		get 'line' => :line
		
	end 
	controller :encountertype do
		get 'viewnow' => :index
		get 'index' => :viewnow
	end 
	
	post "indicators/create" => "indicators#create"
	
	get "indicators/new" => "indicators#new"
	
	get "indicators/destroy" => "indicators#destroy"

	get "indicators/show"	=> "indicators#show"

	get "indicators/edit" => "indicators#edit"
	
	resources :users

	post "sessions/create"
	get "sessions/destroy"
	
	resources :indicators

		

  root 'sessions#new'  

end

app/models/application.rb
class Application < ActiveRecord::Base
end

app/models/available_system.rb
class AvailableSystem < ActiveRecord::Base
end

app/models/encountertype.rb
class Encountertype < ActiveRecord::Base
	establish_connection "other_db"
	self.table_name = "encounter_type"	
	self.primary_key = "encounter_type_id"
	has_one :Tryout, :foreign_key => :creator 
end

app/models/indicator.rb
class Indicator < ActiveRecord::Base
  has_one :users
  has_many :results
end

app/models/indicator_count.rb
class IndicatorCount < ActiveRecord::Base
end

app/models/indie.rb
class Indie < ActiveRecord::Base
	has_many :Sampledata
	has_many :Tryout
end

app/models/result.rb
class Result < ActiveRecord::Base
  has_and_belongs_to_many :indicators
	
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/sampledata.rb
class Sampledata < ActiveRecord::Base
	establish_connection "other_db"
	self.table_name = "users"
	self.primary_key ="user_id"
	has_one :Tryout, :foreign_key => :creator
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/tryout.rb
class Tryout < ActiveRecord::Base
	establish_connection "other_db"	
	self.table_name = "encounter"
	self.primary_key = "encounter_id"
	has_many :Users, :class_name => 'Sampledata', :foreign_key => :creator
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true  
	has_secure_password

	after_destroy :ensure_an_admin_remains
	private
		def ensure_an_admin_remains
			if User.count.zero?
				raise "Cant delete last user"
			end
		end

	has_many :indicator, counter_cache: true
	has_many :available_systems
end

app/models/user_at_site.rb
class UserAtSite < ActiveRecord::Base
end

app/controllers/available_systems_controller.rb
class AvailableSystemsController < ApplicationController
  before_action :set_available_system, only: [:show, :edit, :update, :destroy]

  # GET /available_systems
  # GET /available_systems.json
  def index
    @available_systems = AvailableSystem.all
  end

  # GET /available_systems/1
  # GET /available_systems/1.json
  def show
  end

  # GET /available_systems/new
  def new
    @available_system = AvailableSystem.new
  end

  # GET /available_systems/1/edit
  def edit
  end

  # POST /available_systems
  # POST /available_systems.json
  def create
    @available_system = AvailableSystem.new(available_system_params)

    respond_to do |format|
      if @available_system.save
        format.html { redirect_to @available_system, notice: 'Available system was successfully created.' }
        format.json { render :show, status: :created, location: @available_system }
      else
        format.html { render :new }
        format.json { render json: @available_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /available_systems/1
  # PATCH/PUT /available_systems/1.json
  def update
    respond_to do |format|
      if @available_system.update(available_system_params)
        format.html { redirect_to @available_system, notice: 'Available system was successfully updated.' }
        format.json { render :show, status: :ok, location: @available_system }
      else
        format.html { render :edit }
        format.json { render json: @available_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /available_systems/1
  # DELETE /available_systems/1.json
  def destroy
    @available_system.destroy
    respond_to do |format|
      format.html { redirect_to available_systems_url, notice: 'Available system was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_available_system
      @available_system = AvailableSystem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def available_system_params
      params[:available_system]
    end
end

app/controllers/tryouts.rb
class tryoutsController < ApplicationController
	def index
		@tryouts = Tryout.limit(10)
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/available_systems_helper.rb
module AvailableSystemsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sampled_helper.rb
module SampledHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tryout_helper.rb
module TryoutHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/available_systems/_form.html.erb
<%= form_for(@available_system) do |f| %>
  <% if @available_system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@available_system.errors.count, "error") %> prohibited this available_system from being saved:</h2>

      <ul>
      <% @available_system.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/available_systems/edit.html.erb
<h1>Editing available_system</h1>

<%= render 'form' %>

<%= link_to 'Show', @available_system %> |
<%= link_to 'Back', available_systems_path %>

app/views/available_systems/index.html.erb
<h1>Listing available_systems</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @available_systems.each do |available_system| %>
      <tr>
        <td><%= link_to 'Show', available_system %></td>
        <td><%= link_to 'Edit', edit_available_system_path(available_system) %></td>
        <td><%= link_to 'Destroy', available_system, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Available system', new_available_system_path %>

app/views/available_systems/new.html.erb
<h1>New available_system</h1>

<%= render 'form' %>

<%= link_to 'Back', available_systems_path %>

app/views/available_systems/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_available_system_path(@available_system) %> |
<%= link_to 'Back', available_systems_path %>